"""init

Revision ID: 93f4f5e50ecc
Revises: 
Create Date: 2021-05-05 15:59:59.710116

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '93f4f5e50ecc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'observation',
        sa.Column('uuid', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('positional_accuracy', sa.Integer(), nullable=True),
        sa.Column('taxon_id', sa.Integer(), nullable=True),
        sa.Column('quality_grade', sa.String(), nullable=True),
        sa.Column('observed_on', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('uuid'),
    )
    op.create_table(
        'photo',
        sa.Column('uuid', sa.String(), nullable=False),
        sa.Column('photo_id', sa.Integer(), nullable=True),
        sa.Column('observation_uuid', sa.String(), nullable=True),
        sa.Column('observer_id', sa.Integer(), nullable=True),
        sa.Column('extension', sa.String(), nullable=True),
        sa.Column('license', sa.String(), nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('position', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('uuid'),
    )
    op.create_table(
        'taxon',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ancestry', sa.String(), nullable=True),
        sa.Column('rank', sa.String(), nullable=True),
        sa.Column('rank_level', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('login', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('taxon')
    op.drop_table('photo')
    op.drop_table('observation')
    # ### end Alembic commands ###
